Header slider
Junge-Liberale-BW/JulisBW-App pull request #23
Opened 2020-04-11 16:03 UTC by davidmue0205

Fügt den Header Slider für den Homescreen hinzu.

2020-04-12 13:45 UTC, c64forthewin commented on src/store/index.js
> +      ],
Bitte noch über Store lösen -> soll austauschbar sein

2020-04-12 13:45 UTC, MarvinWank requested changes
Bild-Urls bitte über store laden

2020-04-13 06:57 UTC, davidmue0205 commented on src/store/index.js
> +      ],
Nun ja. Ist das nicht über den Store gelöst. Du referenzierst ja auch auf den Store. Kann aber auch sein, dass ich es falsch verstanden habe.

2020-04-13 10:42 UTC, MarvinWank approved these changes

2020-04-13 10:42 UTC, merged