Navigation fixes
Junge-Liberale-BW/JulisBW-App pull request #39
Opened 2020-04-13 21:29 UTC by davidmue0205

Vielleicht hat noch jemand eine Idee, wie man "Über die App" und Impressum nach unten bekommt.

2020-04-14 20:45 UTC, fmundinger commented
- Menu schließt sich nicht komplett
- dem Design anpassen

2020-06-23 17:02 UTC, MarvinWank requested changes

2020-06-23 17:02 UTC, c64forthewin commented on src/assets/scss/nav.scss
> +  width: 320px;
Führt dazu, dass die Navigation bei manchen Aufösungen dauerhaft angezeigt wird. Getestet mit Firefox devmode 360 * 740px

2020-08-31 18:26 UTC, c64forthewin approved these changes

2020-08-31 18:26 UTC, merged